apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
spec:
  replicas: 3
  selector:
    app: blue
  template:
    metadata:
      name: blue
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: mahdiuzzaman/nginx-hello-world:blue
        ports:
        - containerPort: 80