apiVersion: v1
kind: ReplicationController
metadata:
  name: green
spec:
  replicas: 1
  selector:
    app: green
  template:
    metadata:
      name: green
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: mahdiuzzaman/nginx-hello-world:green
        ports:
        - containerPort: 80
      nodeSelector:
        environment: blue