apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cloudND-cluster
  region: us-west-2  

nodeGroups:
  - name: cloudND
    instanceType: t2.micro
    desiredCapacity: 4
    volumeSize: 8