apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cloudND
  region: us-west-2  

nodeGroups:
  - name: blue
    labels:
      environment: blue
    instanceType: t2.micro
    minSize: 1
    maxSize: 2
    volumeSize: 8
    instanceName: blue

  
  - name: green
    labels:
      environment: green
    instanceType: t2.micro
    minSize: 1
    maxSize: 2
    volumeSize: 8
    instanceName: green